apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "faucet.fullname" . }}
  labels:
    {{- include "faucet.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.app.environment | quote }}
  SERVER_PORT: {{ .Values.app.serverPort | quote }}
  APP_PREFIX: {{ .Values.app.appPrefix | quote }}
  DB_HOST: {{ .Values.app.dbHost | quote }}
  DB_PORT: {{ .Values.app.dbPort | quote }}
  DB_NAME: {{ .Values.app.dbName | quote }}
  QUEUE_HOST: {{ .Values.app.queueHost | quote }}
  QUEUE_PORT: {{ .Values.app.queuePort | quote }}
  PROVIDER: {{ .Values.app.provider | quote }}