version: '3.8'

services:
  main:
    build:
      context: ../../
      target: build
      dockerfile: services/claim-backend/Dockerfile
    command: yarn workspace @taraxa_project/taraxa-claim-backend start:prod
    ports:
      - ${SERVER_PORT}:3000
    volumes:
      - .:/usr/src/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    links:
     - db
  db:
    image: postgres
    restart: always
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
