app:
  environment: prod

  apiHost: "https://api.claim.taraxa.io"

image:
  repository: gcr.io/jovial-meridian-249123/taraxa-claim-admin-main

nodeSelector:
  cloud.google.com/gke-nodepool: taraxa-community-prod

ingress:
  enabled: true
  hosts:
    - host: admin.claim.taraxa.io
  tls:
    - secretName: wild-claim-taraxa-io-tls
      hosts:
        - admin.claim.taraxa.io
