app:
  environment: qa

  apiHost: "https://api.qa.claim.taraxa.io"

image:
  repository: gcr.io/jovial-meridian-249123/taraxa-claim-admin-develop

nodeSelector:
  cloud.google.com/gke-nodepool: taraxa-community-qa

ingress:
  enabled: true
  hosts:
    - host: admin.qa.claim.taraxa.io
  tls:
    - secretName: wild-qa-claim-taraxa-io-tls
      hosts:
        - admin.qa.claim.taraxa.io

