apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "explorer.hash.fullname" . }}
  labels:
    {{- include "explorer.hash.labels" . | nindent 4 }}
spec:
{{- if not .Values.hash.autoscaling.enabled }}
  replicas: {{ .Values.hash.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "explorer.hash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.hash.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "explorer.hash.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.hash.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "explorer.hash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.hash.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.hash.securityContext | nindent 12 }}
          image: "{{ .Values.hash.image.repository }}:{{ .Values.hash.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.hash.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.hash.resources | nindent 12 }}
      {{- with .Values.hash.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hash.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hash.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
