apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "claim-admin.fullname" . }}
  labels:
    {{- include "claim-admin.labels" . | nindent 4 }}
data:
  REACT_APP_BASE_URL: {{ .Values.app.apiHost | quote }}
