replicaCount: 2

appSecret:
  # should we create secrets ?
  # set to 'false' when supplying secrets from i.e. SealedSecrets controller
  create: true 

app:
  name: community-backend
  component: api

  environment: default
  url: https://api.default.community.taraxa.io
  dbHost: default-db.address
  dbName: taraxa-community-default
  uploadBucketName: taraxa-community-default
  explorerUrl: http://explorer.default.taraxa.io

  serverPort: 1337
  dbPort: 5432

  # secrets
  secrets:
    recaptchaSecret: ''
    communityPrivKey: ''
    dbUsername: ''
    dbPassword: ''
    jwtSecret: ''
    kycApiToken: ''
    kycApiSecret: ''
    sendgridApiKey: ''
    serviceAccount: ''



nodeSelector:
  cloud.google.com/gke-nodepool: taraxa-community-default

image:
  repository: gcr.io/jovial-meridian-249123/taraxa-community-server-develop
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

tolerations: []

affinity: {}

