apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "explorer-api.fullname" . }}
  labels:
    {{- include "explorer-api.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.app.environment | quote }}
  SERVER_PORT: {{ .Values.app.serverPort | quote }}
  APP_PREFIX: {{ .Values.app.appPrefix | quote }}
  DB_HOST: {{ .Values.app.dbHost | quote }}
  DB_PORT: {{ .Values.app.dbPort | quote }}
  DB_NAME: {{ .Values.app.dbName | quote }}
  TOKEN_PRICE_API_ENDPOINT: {{ .Values.app.tokenPriceApiEndpoint | quote }}