apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-error-community
  labels:
    app: custom-error-community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-error-community
  template:
    metadata:
      labels:
        app: custom-error-community
    spec:
      serviceAccountName: {{ include "community.frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: custom-error-community
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: hashicorp/http-echo
          args:
            - "-text=<HTML>

<HEAD>

<TITLE>We're sorry...</TITLE>

</HEAD>

<HR>

<H1>We're sorry... </H1>

Unfortunately United States persons are unable to participate in our community activities.

Please contact us at <a href='mailto:support@taraxa.io'>

support@taraxa.io</a>.

<HR>

</BODY>

</HTML>
"
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.frontend.customError.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
kind: Service
apiVersion: v1
metadata:
  name: custom-error-community-service
spec:
  selector:
    app: custom-error-community
  ports:
    - port: 5678 # Default port for image
